name: Stream Processor
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: raw-temp-data
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: agg-temperature
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
